version: '3'

services:
  comments-api-nginx:
    container_name: comments-api-nginx
    image: nginx:1.21-alpine
    restart: on-failure
    volumes:
      - './comments-api:/var/www/app'
      - './docker/nginx/api_default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - "8081:80"
    depends_on:
      - comments-api-php

  comments-api-php:
    container_name: comments-api-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - comments-api/.env
    user: 1000:1000
    volumes:
      - ./comments-api:/var/www/app

  comments-api-mysql:
    container_name: comments-api-mysql
    image: mysql:8.0.23
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: dfbsdbdfbdfb
    ports:
      - "3306:3306"

  comments-front-nginx:

    container_name: comments-front-nginx
    image: nginx:1.21-alpine
    restart: on-failure
    volumes:
      - './comments-front:/var/www/app'
      - './docker/nginx/front_default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - "8082:80"
    depends_on:
      - comments-front-php

  comments-front-php:
    container_name: comments-front-php
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    env_file:
      - comments-front/.env
    user: 1000:1000
    volumes:
      - ./comments-front:/var/www/app