doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Comment:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Comments/Infrastructure/DoctrineMapping'
                prefix: 'App\Comments\Domain\Entity'
                alias: Comment
